sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product tstn-018
env:
  global:
    -
      # LTD_AWS_ID
      secure: rxMILsBTVOsStiFmac0mTIHf+bP6YXYbSIribGuvYWsHuwztHRhNz4ToG3pF1JOGCO/e+kzprXed6ybxkr6kuOZOE3PY7z3fGKYseOJmj3KiRvWGCT+9Lkl4Bt8riWdHE8AsCG0um/zsRZ1XYmoDb5kxJM1yyNaGvbH8ZCOK76ToLN99Lxh/4H8XcZC2604/TWDxVLZ+ej6YmHgyt8f3FFws9XkfGbw01RKDuSM/jTifL+V3OSyloBL1weyd7I1vjncQhEbqgjN+7li4+Bp6amKVSfJm0Tw0jyAjpD8b4Vhy1WD0xoQJZTMepxZTFYVROovKyQ8cI/q9kBKZ/QggIThL9GK0iYHnUNr3dNydXoW+OxMQqMkXA30qzpq8ZprgaGDG0o3Jpmq5KGIjjUDp3XIg+dABONZXGIhqCaUuffC7kWR4PWd+AdBpswXpSGPCR80ezSFEkWgwwwFVqw+1s/cEBQMV0hctgAZL4cabQA6DJLr6iQUOuyKX3feTjf4SILOlhPbBJT8AoDQ3GLmUYkqAIAJyu5MAgaoh0m1g6Av2O9cs/imCi0snYoueH+rWML9Rm6cz6g8V/WlklpCbLDx1V2lM8o09XMaHCL6NReGi0GbZMi44R7rdvESLeUznU+PNcPPsSQdJC4DgOPNLuUkQ9vYdBPJSRcZwW8znH5c=
    -
      # LTD_AWS_SECRET
      secure: EWDRWiuNKZzR0z4OSBWIOPd25L1f7Xk7/shDRIhqUg43icCfA9aSTWIpuzetwJB0Sc7KD1q3jrJIe1TDWZj8rq47rPuMdK4GoweteORG+E/FXqcsYT+8dikzcI2Az+Amj+cUPkJJw0pGq+GQGT6/Hy+ySGUmvP7tZLGxHfPx5dX4Dy9e++L4CJ3t9trqrj3GE+cbahOcKmugStaSqjgLBszh51t0vuK18/CkG1ubm37Be2dYIcYylXZSZYen5nUaQBfzKSTXKzmAJMecHRpeHEjzyHzldivo8z29kygD3cOC71yyBiFDxK/GwYkDUK/+NCE+MH/TrjzAywvQ7mqTvv5qIjkcEMK75snkCMzR4y06/D1Nm9zmGClVMdLWuelDJwz5Ae6irv/asqspJAQVq2vaYr0704fPjcXrEe0NRGFMIKhGnDtF33v1R+LKthDM9L4O1KBiCLy7iIq4JxjYtzglW+W+bGJ1Z/HjKR4n1wML1HeePwe0vNkT0dHPGSMxEyOsYisbS+eVr0t3SuGDP59hgukOS4s/gt8v8ThU1SQSUZ6jt9AFyHHyZygWAyUivCzr4rgC67In0RBzY3hWaOeSHUvq6y5raCxFovRCY1x07MI2qSCqs4h1pigFhOmWM+ha3RexwAgtck5X9g+vFrbgTorLxiPedGRCE8fRwzI=
    -
      # LTD_USERNAME
      secure: X2+vTw79gCu4nMR92TasNHkIspL5VDQ5yxkXkTvVJu8ANN4EKh5z391VYSbSzDy0mGE0+jSFltuuXL0Yghi37pDaU+bN9YU4zJps7r1GE17vVcZnDIBaJzaGTykdJN7q8ybNTIJKBvh/js8iCnRf+9ycms1sUPYdnMSRGeWBpWn7uB28XZjwk5g/EMSZEuQEsYzkdsjVoSKOgWGCd07QawsqxAIIYGqBFBg6vBqyB778q2xMgd6HjPUbbprkZ4abwRSLEq6DIfzfHWpX9lHSfX/2yAfUuNtSNVtaU1GR/OeUxTtjpqqOEbCsC4koEHJ4wmKTmdayA6QH38KPzHmRGd+xPsRxOUYQuwTXVg6i0dq9wlxFJ+ZQ7Ps0X7UdfuMFYKxF8RQNnE3EsBV7qI1agn/uXyn1Khq7ZdV6kYX5v0r0Awc0NLfgG3/OGyLFCqeg58/odvnwYP6192nR+i8FeeyzTX/N8CilTV41HK00s+Ovg56/OwSrLOlhDarO1biGJbcovuv+847mmm5u/fZffJTyE+2qmU6q58ZnmziMQ8dcOLk66svlMnAsUDSAqxrfKAMPW1O2mTzChkJqGWeluOP0VHIhkKaT8DcGlFAux8I1suj7jJVy4HTvmCniufm5TNpS0i6xnPSXRzT1R2rxrpU+Jo07ziHf5KyEhdV9K5E=
    -
      # LTD_PASSWORD
      secure: WGCCpGBhxTRAe8IF5Lo43GdWLQueBAbFEtN0UNCD02H2yB2LO65umjvmEteZzdX7/MgbRBnHSpVdqEtioV/uyiDha0NZ3h+HjrTJFrqPreqXibtp2HuCQR6Wb80t5QWLtCyxZ6/pWTKsPPpqxc48eiRBExRlfWSbUT8mpOsg3ieq6rP56kgUvficWUMZ9c9vC4CJ3OI0+SbxbQYxuCg2xSvMZEbM2FKXCfv7VMOQx3MSLO5NtGpG0tPt0lhm7cl8A6MKOwsZpcRDuQXsWwsivSEbMrTnTanMGy1ww78qU3xkHNs9ALUCFATy6tkqaeU5B7KOXFgxWRDqyswHJSrn5+dsvzrkXLrGhj3IeZ2yqpyOqFzTZFTcH1/OuSl695EtTsgsRubYtlPd5BbqALZnMh/7X+h82a8EvkJuFEHiPSsqLH/NpcgSVA38fMUgkl/6M10+w+ckLo1S+8Aey+oCyj0ouGqHuPyukk8MesOaO/Mw/23eX3JqSllHJfW+L3dIVGz3TxyJVmV44Ovj2ugOatITSVnGKArGqjA1uRGIRG1Sdoa9sKpaccEVV9ZaNMNxlAn56ocZ3ErqF0QrLnsKZ/V94Bis0e7z6OTyJk8MZyCPkgFOJO297QW6+6TR7OfzVnJMtA8dDX0srtWXgP6Utyp+Oz4DLahr6aMhwV/bcUY=
